import { NextRequest, NextResponse } from 'next/server'

// Product catalog (same as in /api/products)
const products = [
  {
    id: 'prod-1',
    slug: 'relaxed-fit-cotton-tee',
    name: 'Relaxed Fit Cotton Tee',
    description: 'Comfortable cotton t-shirt with relaxed fit, perfect for everyday wear. Made from 100% premium cotton for breathability and comfort.',
    price: 179000,
    originalPrice: 229000,
    category: 'tops',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Black', 'Navy', 'Grey'],
    rating: 4.6,
    reviewCount: 189,
    soldCount: 892,
    inStock: true,
    images: ['/products/cotton-tee-1.jpg', '/products/cotton-tee-2.jpg'],
    material: '100% Cotton',
    care: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
  },
  {
    id: 'prod-2',
    slug: 'vintage-wash-tshirt',
    name: 'Vintage Wash T-Shirt',
    description: 'Soft vintage-washed cotton tee with a lived-in look. Pre-washed for extra softness.',
    price: 199000,
    originalPrice: null,
    category: 'tops',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Dusty Blue', 'Sage', 'Cream'],
    rating: 4.8,
    reviewCount: 234,
    soldCount: 1250,
    inStock: true,
    images: ['/products/vintage-tee-1.jpg'],
    material: '100% Cotton',
    care: ['Machine wash cold', 'Hang dry'],
  },
  {
    id: 'prod-3',
    slug: 'high-waist-straight-jeans',
    name: 'High Waist Straight Jeans',
    description: 'Classic high-waisted jeans with straight leg silhouette. Comfortable stretch denim.',
    price: 399000,
    originalPrice: 499000,
    category: 'bottoms',
    sizes: ['26', '27', '28', '29', '30', '31', '32'],
    colors: ['Light Blue', 'Dark Blue', 'Black'],
    rating: 4.7,
    reviewCount: 312,
    soldCount: 2100,
    inStock: true,
    images: ['/products/jeans-1.jpg', '/products/jeans-2.jpg'],
    material: '98% Cotton, 2% Elastane',
    care: ['Machine wash cold', 'Tumble dry low'],
  },
  {
    id: 'prod-4',
    slug: 'wide-leg-palazzo-pants',
    name: 'Wide Leg Palazzo Pants',
    description: 'Flowy palazzo pants with wide leg and elastic waist. Elegant and comfortable.',
    price: 349000,
    originalPrice: null,
    category: 'bottoms',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'Cream', 'Olive'],
    rating: 4.4,
    reviewCount: 98,
    soldCount: 430,
    inStock: true,
    images: ['/products/palazzo-1.jpg'],
    material: '100% Polyester',
    care: ['Machine wash cold', 'Hang dry'],
  },
  {
    id: 'prod-5',
    slug: 'pleated-midi-skirt',
    name: 'Pleated Midi Skirt',
    description: 'Elegant pleated skirt in midi length, perfect for office or casual wear.',
    price: 279000,
    originalPrice: null,
    category: 'bottoms',
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Navy', 'Dusty Pink'],
    rating: 4.6,
    reviewCount: 167,
    soldCount: 789,
    inStock: true,
    images: ['/products/skirt-1.jpg'],
    material: '100% Polyester',
    care: ['Hand wash', 'Hang dry'],
  },
  {
    id: 'prod-6',
    slug: 'floral-wrap-dress',
    name: 'Floral Wrap Dress',
    description: 'Beautiful wrap dress with floral print, flattering for all body types. V-neck design with tie waist.',
    price: 449000,
    originalPrice: 549000,
    category: 'dresses',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue Floral', 'Pink Floral', 'Green Floral'],
    rating: 4.9,
    reviewCount: 203,
    soldCount: 567,
    inStock: true,
    images: ['/products/wrap-dress-1.jpg', '/products/wrap-dress-2.jpg'],
    material: '100% Viscose',
    care: ['Hand wash', 'Hang dry'],
  },
  {
    id: 'prod-7',
    slug: 'linen-midi-dress',
    name: 'Linen Midi Dress',
    description: 'Breathable linen dress perfect for warm weather. Relaxed fit with side pockets.',
    price: 399000,
    originalPrice: null,
    category: 'dresses',
    sizes: ['S', 'M', 'L'],
    colors: ['White', 'Beige', 'Light Blue'],
    rating: 4.7,
    reviewCount: 145,
    soldCount: 456,
    inStock: true,
    images: ['/products/linen-dress-1.jpg'],
    material: '100% Linen',
    care: ['Machine wash cold', 'Hang dry', 'Iron while damp'],
  },
  {
    id: 'prod-8',
    slug: 'chunky-knit-cardigan',
    name: 'Chunky Knit Cardigan',
    description: 'Cozy oversized cardigan in chunky knit, perfect for layering. Button-front closure.',
    price: 449000,
    originalPrice: 549000,
    category: 'outerwear',
    sizes: ['S/M', 'L/XL'],
    colors: ['Cream', 'Grey', 'Brown'],
    rating: 4.8,
    reviewCount: 189,
    soldCount: 890,
    inStock: true,
    images: ['/products/cardigan-1.jpg', '/products/cardigan-2.jpg'],
    material: '50% Wool, 50% Acrylic',
    care: ['Hand wash cold', 'Lay flat to dry'],
  },
  {
    id: 'prod-9',
    slug: 'cropped-denim-jacket',
    name: 'Cropped Denim Jacket',
    description: 'Classic denim jacket with cropped length, versatile wardrobe staple. Button closure with chest pockets.',
    price: 499000,
    originalPrice: null,
    category: 'outerwear',
    sizes: ['S', 'M', 'L'],
    colors: ['Light Wash', 'Medium Wash', 'Black'],
    rating: 4.6,
    reviewCount: 123,
    soldCount: 345,
    inStock: true,
    images: ['/products/denim-jacket-1.jpg'],
    material: '100% Cotton Denim',
    care: ['Machine wash cold', 'Tumble dry low'],
  },
  {
    id: 'prod-10',
    slug: 'minimal-canvas-tote',
    name: 'Minimal Canvas Tote',
    description: 'Simple and durable canvas tote bag for everyday use. Spacious interior with inner pocket.',
    price: 199000,
    originalPrice: null,
    category: 'accessories',
    sizes: ['One Size'],
    colors: ['Natural', 'Black', 'Navy'],
    rating: 4.5,
    reviewCount: 87,
    soldCount: 234,
    inStock: true,
    images: ['/products/tote-1.jpg'],
    material: '100% Canvas',
    care: ['Spot clean'],
  },
  {
    id: 'prod-11',
    slug: 'gold-hoop-earrings',
    name: 'Gold Hoop Earrings',
    description: 'Classic gold-plated hoop earrings, timeless accessory. Lightweight and comfortable.',
    price: 149000,
    originalPrice: null,
    category: 'accessories',
    sizes: ['Small', 'Medium', 'Large'],
    colors: ['Gold'],
    rating: 4.7,
    reviewCount: 156,
    soldCount: 567,
    inStock: true,
    images: ['/products/earrings-1.jpg'],
    material: '18K Gold Plated',
    care: ['Keep dry', 'Store in jewelry box'],
  },
  {
    id: 'prod-12',
    slug: 'silk-scarf',
    name: 'Printed Silk Scarf',
    description: 'Luxurious silk scarf with artistic print, versatile styling options. Can be worn as headscarf, necktie, or bag accessory.',
    price: 299000,
    originalPrice: 399000,
    category: 'accessories',
    sizes: ['One Size'],
    colors: ['Blue Pattern', 'Red Pattern', 'Green Pattern'],
    rating: 4.8,
    reviewCount: 92,
    soldCount: 178,
    inStock: true,
    images: ['/products/scarf-1.jpg'],
    material: '100% Silk',
    care: ['Dry clean only'],
  },
]

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params
  const product = products.find(p => p.slug === slug || p.id === slug)

  if (!product) {
    return NextResponse.json(
      {
        success: false,
        error: {
          code: 'PRODUCT_NOT_FOUND',
          message: `Product with slug "${slug}" not found`,
        },
      },
      { status: 404 }
    )
  }

  // Generate variants
  const variants = []
  for (const size of product.sizes) {
    for (const color of product.colors) {
      variants.push({
        id: `${product.id}-${size}-${color}`.toLowerCase().replace(/\s+/g, '-'),
        productId: product.id,
        size,
        color,
        price: product.price,
        inStock: true,
        stockQuantity: Math.floor(Math.random() * 20) + 5,
      })
    }
  }

  return NextResponse.json({
    success: true,
    data: {
      ...product,
      variants,
    },
    meta: {
      currency: 'IDR',
    },
  })
}
